### ISSUE TITLE
Does not appear to work with new 4k Fire TV (Dongle version)

### ISSUE THREAD

**Issue by pstuart** [ZaneH/firetv-remote#1]
Looks like Amazon closed the ADB remote connection.  I can't get this to control a new 4k fire tv plug in dongle (not the stick).

Any ideas?

**Comment by ZaneH** [comment]
Is ADB debugging turned on?

If it still doesn't work, I imagine Amazon changed the shell codes for the remote control.

Starts here: https://github.com/ZaneH/FireTVRemote-Node/blob/f03ec52bbc3ecd5058e5bef26393eb969a884aed/routes/index.js#L34

**Comment by pstuart** [comment]
Adb debugging is on. Was able to connect via my phone with a newer version of advice which pops up a prompt on fire TV to allow device access to adb or not. So it appears the version of adb included in this doesn't support authentication.

**Comment by ZaneH** [comment]
https://github.com/ZaneH/FireTVRemote-Node/tree/fix-new-devices

Can you give that a try? I haven't tested it, but I updated the `adb` binary.

**Comment by pstuart** [comment]
Thanks for the update, however that didn't fix it.  Still doesn't pop up the authorization on the fire tv UI.  With latest ADB from a windows shell, when I connect I get an authorize this device yes/no and then the normal shell commands work just fine.

**Comment by GastroGeek** [comment]
To get this working on latest 4K Fire TV:

* Enable ADB debugging on Fire TV Stick
* Overwrite the adb executable using a newer version: 1.0.29 => 1.0.40

**Comment by phuockal** [comment]
I wonder why "right" and "next" has the same value 22; "left" and "last" has the same value 21
thanks

**Comment by ZaneH** [comment]
I've added a note to the top of the `README.md` to redirect people to this issue in the future. I'm glad you were able to get it working with the 4K version @GastroGeek

> I wonder why "right" and "next" has the same value 22; "left" and "last" has the same value 21 thanks

Maybe this was a mistake on my part, but I feel like I remember them having the same codes in my testing. It kind of makes sense that right & next would be synonymous here.
