### ISSUE TITLE
$ node ./app.js doesn't appear to do anything

### ISSUE THREAD

**Issue by iconoclasthero** [ZaneH/firetv-remote#5]
No window popped, the active Chrome session doesn't come to the fore, it just does it's thing and exits without seeming to do anything.  I ran it with debug options:  

`$ NODE_DEBUG=cluster,net,http,fs,tls,module,timers node app.js 2>app.js.log`

https://pastebin.com/b9vNF8AB (This paste is set to expire in 6 months so copy it if you need it for anything beyond that.)

System info:
Ubuntu 22.10
node --version: v18.7.0
Firestick 4K

**Comment by ZaneH** [comment]
Did you open chrome and see if `http://localhost:3000` works? It doesn't open chrome automatically as it's purely a Node.js app. Since I didn't see any errors in your log, I'm suspecting it is mostly working– you may have to reference Issue #1 as well to fix for Firestick 4K.

**Comment by ZaneH** [comment]
> No window popped, the active Chrome session doesn't come to the fore, it just does it's thing and exits without seeming to do anything. I ran it with debug options:
> 
> `$ NODE_DEBUG=cluster,net,http,fs,tls,module,timers node app.js 2>app.js.log`
> 
> https://pastebin.com/b9vNF8AB (This paste is set to expire in 6 months so copy it if you need it for anything beyond that.)
> 
> System info: Ubuntu 22.10 node --version: v18.7.0 Firestick 4K

Just tried running this locally and ran into what you experienced. The original `README.md` should've said use `$ npm run start` to start the app.
